Search.appendIndex(
    [
                {
            "fqsen": "\\sumar\u0028\u0029",
            "name": "sumar",
            "summary": "Funci\u00F3n\u0020para\u0020sumar\u0020dos\u0020n\u00FAmeros.",
            "url": "namespaces/default.html#function_sumar"
        },                {
            "fqsen": "\\multiplicar\u0028\u0029",
            "name": "multiplicar",
            "summary": "Funci\u00F3n\u0020para\u0020multiplicar\u0020dos\u0020n\u00FAmeros.",
            "url": "namespaces/default.html#function_multiplicar"
        },                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Clase\u0020para\u0020manejo\u0020de\u0020usuarios.",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020Usuario.",
            "url": "classes/Usuario.html#method___construct"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "Obtiene\u0020el\u0020nombre\u0020del\u0020usuario.",
            "url": "classes/Usuario.html#method_getNombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNombre\u0028\u0029",
            "name": "setNombre",
            "summary": "Establece\u0020el\u0020nombre\u0020del\u0020usuario.",
            "url": "classes/Usuario.html#method_setNombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetEdad\u0028\u0029",
            "name": "getEdad",
            "summary": "Obtiene\u0020la\u0020edad\u0020del\u0020usuario.",
            "url": "classes/Usuario.html#method_getEdad"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetEdad\u0028\u0029",
            "name": "setEdad",
            "summary": "Establece\u0020la\u0020edad\u0020del\u0020usuario.",
            "url": "classes/Usuario.html#method_setEdad"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "",
            "url": "classes/Usuario.html#property_nombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024edad",
            "name": "edad",
            "summary": "",
            "url": "classes/Usuario.html#property_edad"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
